//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeaway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemFood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemFood()
        {
            this.ItemFoodDetails = new HashSet<ItemFoodDetail>();
            this.ItemFoodRates = new HashSet<ItemFoodRate>();
            this.ItemFoodTypes = new HashSet<ItemFoodType>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long ID { get; set; }
        public string FoodName { get; set; }
        public string FoodNameEn { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public int CategoryID { get; set; }
        public int CategoryTypeID { get; set; }
        public bool NotforSale { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public bool IsActive { get; set; }
        public bool IsDetete { get; set; }
        public Nullable<int> SizeID { get; set; }
        public bool IsCooking { get; set; }
    
        public virtual ItemFood ItemFood1 { get; set; }
        public virtual ItemFood ItemFood2 { get; set; }
        public virtual Category Category { get; set; }
        public virtual CategoryType CategoryType { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemFoodDetail> ItemFoodDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemFoodRate> ItemFoodRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemFoodType> ItemFoodTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
