//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeaway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantRate
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public int RestaurantID { get; set; }
        public decimal UserRate { get; set; }
        public int RateType { get; set; }
        public bool IsActive { get; set; }
        public bool IsDetete { get; set; }
    
        public virtual RateType RateType1 { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
