//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeaway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemFoodType
    {
        public int ID { get; set; }
        public long ItemFoodID { get; set; }
        public int FoodTypeID { get; set; }
    
        public virtual FoodType FoodType { get; set; }
        public virtual ItemFood ItemFood { get; set; }
    }
}
