//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeaway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public string DeliveryUserID { get; set; }
        public int RestaurantDataID { get; set; }
        public int OrderStatusID { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal FeeValue { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.TimeSpan> Delivery_estimation { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public bool IsDetete { get; set; }
        public Nullable<int> RestOfferID { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public bool OneMachine { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual RestaurantData RestaurantData { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
