//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeaway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public long ItemFoodID { get; set; }
        public Nullable<long> ItemFoodParentID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> CookingCatID { get; set; }
        public decimal ItemPrice { get; set; }
        public int ItemCount { get; set; }
        public bool IsActive { get; set; }
        public bool IsDetete { get; set; }
        public Nullable<int> ItemOfferID { get; set; }
    
        public virtual CookingCategory CookingCategory { get; set; }
        public virtual ItemFood ItemFood { get; set; }
        public virtual Order Order { get; set; }
    }
}
