//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeaway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Address { get; set; }
        public int Region_id { get; set; }
        public string MapLatitude { get; set; }
        public string MapLongitude { get; set; }
        public bool IsActive { get; set; }
        public bool IsDetete { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual User User { get; set; }
    }
}
